version: '3.8'

services:
  staging:
    build: .
    ports:
      - 8000:8000
    environment:
      - RUST_LOG=info
      - APP_ENV=staging
    volumes:
      - .:/usr/src/klearlink-api
    command: ["cargo", "run", "--release"]
  production:
    build: .
    ports:
      - 8000:8000
    environment:
      - RUST_LOG=info
      - APP_ENV=production
    volumes:
      - .:/usr/src/klearlink-api
    command: ["cargo", "run", "--release"]
