version: '3.8'

services:
  staging:
    build: .
    ports:
      - 8000:8000
    environment:
      - RUST_LOG=info
      - ROCKET_ENV=staging
    command: ["/app/klearlink-api"]

  production:
    build: .
    ports:
      - 8000:8000
    environment:
      - RUST_LOG=info
      - ROCKET_ENV=production
    command: ["/app/klearlink-api"]
