name: staging

on:
  push:
    branches:
      - main
    paths:
      - "src/**/*.rs"

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Notify
        run: echo "Building and releasing staging!"

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build Docker image
        run: docker compose build staging

      - name: Push Docker image
        run: docker compose push staging
